name = "1.21.1 Fantasy"
author = "usersina"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2d1bc14317722045006058951c1927c44c490fcd9fa00f5e1969e0d6d81acf7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"

[options]
acceptable-game-versions = ["list"]
datapack-folder = "config/paxi/datapacks"
