name = "1.21.1 Fantasy"
author = "usersina"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c55cdb683a9d16bb512737e4e0cfa5e1e8e03fcb3809ab18cff7038f56a2f95"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
