name = "1.21.1 Fantasy"
author = "usersina"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a94a7d1c0d9a8c5ad35e1db003a0c52e0e805ab6e57a1fe9450b71135c72f08f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"

[options]
acceptable-game-versions = ["list"]
datapack-folder = "config/paxi/datapacks"
