modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="vampire_cauldron_blood_fix"
version="1.0.0"
displayName="Undead Cauldron Blood Fix"
authors="usersina"
description='''Prevents vampires and other undead creatures from bleeding into Iron's Spells blood cauldrons.'''

[[dependencies.vampire_cauldron_blood_fix]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.vampire_cauldron_blood_fix]]
modId="neoforge"
type="required"
versionRange="[21.1,21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.vampire_cauldron_blood_fix]]
modId="irons_spellbooks"
type="required"
versionRange="[1.21.1-3.16.2,1.21.1-3.17.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.vampire_cauldron_blood_fix]]
modId="vampirism"
type="required"
versionRange="[1.10.12,1.11.0)"
ordering="AFTER"
side="BOTH"
